# Generated by Django 3.2.8 on 2021-11-10 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shamart', '0002_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
