# Generated by Django 3.2.8 on 2021-11-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_items_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartlist',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
