# Generated by Django 3.2.8 on 2021-11-18 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cartlist_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartlist',
            name='user_id',
        ),
    ]
